# Generated by Django 3.2.25 on 2025-05-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.CharField(help_text='ID of the medicine (from Medicine service) or other supply/equipment', max_length=100)),
                ('item_type', models.CharField(choices=[('medicine', 'Medicine'), ('supply', 'Medical Supply'), ('equipment', 'Medical Equipment')], default='medicine', max_length=20)),
                ('item_name', models.CharField(help_text='Name of the item (can be denormalized from medicine service or entered for supplies)', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('location_id', models.CharField(help_text='ID of the pharmacy, hospital ward, or storage unit', max_length=100)),
                ('location_type', models.CharField(choices=[('pharmacy', 'Pharmacy'), ('hospital_ward', 'Hospital Ward'), ('hospital_storage', 'Hospital Central Storage'), ('clinic', 'Clinic')], max_length=30)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measure', models.CharField(default='unit', help_text='e.g., tablets, ml, box, unit', max_length=50)),
                ('batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, help_text='For individual trackable items like equipment', max_length=100, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('selling_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Can also be managed by pharmacy/billing service', max_digits=10, null=True)),
                ('reorder_level', models.PositiveIntegerField(default=10)),
                ('supplier_id', models.CharField(blank=True, help_text='Reference to a supplier service or ID', max_length=100, null=True)),
                ('last_restock_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, help_text='e.g., Available, Low Stock, Out of Stock, Recalled', max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('medicine_detail_id', models.CharField(blank=True, help_text='Corresponds to the ID in the Medicine service if this is a medicine', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'db_table': 'inventory_items',
            },
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['item_id', 'item_type'], name='inventory_i_item_id_139544_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['location_id', 'location_type'], name='inventory_i_locatio_ee3973_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['expiration_date'], name='inventory_i_expirat_86e7b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('location_id', 'location_type', 'item_id', 'batch_number', 'serial_number')},
        ),
    ]
