version: '3.8'

services:
  db:
    image: mysql:9.3.0
    restart: always
    environment:
      MYSQL_DATABASE: healthcare
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
