# Generated by Django 3.2.18 on 2025-05-17 15:40

from django.db import migrations, models
import medicine_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('manufacturer', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('dosage_form', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('ndc_code', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('is_controlled_substance', models.BooleanField(default=False)),
                ('control_class', models.CharField(blank=True, max_length=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side_effects', medicine_service.models.ListField(default=list)),
                ('interactions', medicine_service.models.ListField(default=list)),
                ('contraindications', medicine_service.models.ListField(default=list)),
                ('active_ingredients', medicine_service.models.ListField(default=list)),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
    ]
