# Generated by Django 3.2.25 on 2025-05-20 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of the user account for this insurance provider liaison', null=True, unique=True)),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('provider_id_number', models.CharField(help_text='Official ID of the insurance company', max_length=50, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider currently active for new policies/claims?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Insurance Provider Company',
                'verbose_name_plural': 'Insurance Provider Companies',
                'db_table': 'insurance_provider_companies',
                'ordering': ['company_name'],
            },
        ),
    ]
