# Generated by Django 3.2.25 on 2025-05-19 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_provider_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceprovider',
            options={'ordering': ['company_name'], 'verbose_name': 'Insurance Provider Company', 'verbose_name_plural': 'Insurance Provider Companies'},
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this provider currently active for new policies/claims?'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='provider_id_number',
            field=models.CharField(default=0, help_text='Official ID of the insurance company', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='company_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_provider_liaison_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='insuranceprovider',
            table='insurance_provider_companies',
        ),
    ]
