# Generated by Django 4.1.13 on 2025-05-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacist',
            name='pharmacy_name',
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='pharmacy_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
