# Generated by Django 3.2.25 on 2025-05-20 03:43

from django.db import migrations, models
import djongo.models.fields
import medical_record_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('visit_date', models.DateTimeField()),
                ('visit_type', models.CharField(choices=[('INITIAL', 'Initial Visit'), ('FOLLOW_UP', 'Follow-up Visit'), ('EMERGENCY', 'Emergency Visit'), ('ROUTINE', 'Routine Checkup'), ('SPECIALIST', 'Specialist Consultation'), ('SURGERY', 'Surgical Procedure'), ('TELEMEDICINE', 'Telemedicine Visit')], max_length=50)),
                ('provider_id', models.CharField(max_length=50)),
                ('chief_complaint', models.TextField()),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('vital_signs', djongo.models.fields.ArrayField(blank=True, model_container=medical_record_service.models.VitalSign, model_form_class=medical_record_service.models.VitalSignForm, null=True)),
                ('notes', djongo.models.fields.ArrayField(blank=True, model_container=medical_record_service.models.Note, model_form_class=medical_record_service.models.NoteForm, null=True)),
                ('attachments', djongo.models.fields.ArrayField(blank=True, model_container=medical_record_service.models.Attachment, model_form_class=medical_record_service.models.AttachmentForm, null=True)),
                ('allergies', medical_record_service.models.ListField(default=list)),
                ('medications', medical_record_service.models.ListField(default=list)),
                ('procedures', medical_record_service.models.ListField(default=list)),
                ('lab_results', medical_record_service.models.ListField(default=list)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient_id'], name='medical_rec_patient_98186b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['record_id'], name='medical_rec_record__3cee9d_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['visit_date'], name='medical_rec_visit_d_9bd080_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['provider_id'], name='medical_rec_provide_2dbe34_idx'),
        ),
    ]
