# Generated by Django 3.2.25 on 2025-05-19 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(help_text='ID of the patient from the User service', max_length=100)),
                ('service_type', models.CharField(choices=[('pharmacy', 'Pharmacy Order'), ('hospital_fee', 'Hospital Fee'), ('consultation', 'Doctor Consultation')], max_length=50)),
                ('originating_service_record_id', models.CharField(help_text='ID of the record in the originating service, e.g., Order ID, Appointment ID', max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_provider_id', models.CharField(blank=True, help_text='ID of the insurance provider, if any', max_length=100, null=True)),
                ('amount_covered_by_insurance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_due_by_patient', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('processing_insurance', 'Processing Insurance'), ('awaiting_patient_payment', 'Awaiting Patient Payment'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=30)),
                ('transaction_details', models.JSONField(blank=True, default=dict, help_text='Details of billable items', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaimProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_provider_id', models.CharField(help_text='ID of the insurance provider', max_length=100)),
                ('claim_identifier', models.CharField(blank=True, help_text='Identifier for the claim given by the insurer', max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted to Insurer'), ('processing', 'Insurer Processing'), ('approved', 'Approved by Insurer'), ('rejected', 'Rejected by Insurer'), ('requires_information', 'Requires More Information'), ('paid', 'Paid by Insurer')], default='submitted', max_length=30)),
                ('amount_claimed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_approved', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('payment_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claim', to='payment_service.paymenttransaction')),
            ],
            options={
                'db_table': 'insurance_claims_processing',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
