# Generated by Django 3.2.25 on 2025-05-19 03:29

from django.db import migrations, models
import djongo.models.fields
import prescription_service.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.CharField(max_length=50, unique=True)),
                ('patient_id', models.CharField(max_length=50)),
                ('doctor_id', models.CharField(max_length=50)),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.TextField()),
                ('medications', djongo.models.fields.ArrayField(model_container=prescription_service.models.MedicationItem, model_form_class=prescription_service.models.MedicationItemForm)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('DISPENSED', 'Dispensed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pharmacy_id', models.CharField(blank=True, max_length=50, null=True)),
                ('dispense_date', models.DateTimeField(blank=True, null=True)),
                ('is_refillable', models.BooleanField(default=False)),
                ('refill_count', models.IntegerField(default=0)),
                ('max_refills', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'prescriptions',
            },
        ),
    ]
