# Generated by Django 3.2.18 on 2025-05-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
    ]
