# Generated by Django 4.1.13 on 2025-05-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacist_service', '0002_remove_pharmacist_pharmacy_name_and_more'),
        ('pharmacy_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacist_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacists',
            field=models.ManyToManyField(blank=True, related_name='pharmacies', to='pharmacist_service.pharmacist'),
        ),
    ]
