# Generated by Django 4.1.13 on 2025-05-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_service', '0002_inventory_notes_inventory_supplier_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='pharmacists',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='pharmacist_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
