# Generated by Django 3.2.25 on 2025-05-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_service', '0003_remove_pharmacy_pharmacists_pharmacy_pharmacist_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='medicine_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='inventory_item_id',
            field=models.CharField(default=0, help_text='ID of the InventoryItem from inventory_service', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
